### ISSUE TITLE
[crash/severe] libtorrent::upnp(weak_ptr, enable_if, is_convertible, value, type) - update_map

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#165]
Over 1,200 crash reports a day.

```
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)
_ZNSt6__ndk110shared_ptrIN10libtorrent4upnpEEC2IS2_EERKNS_8weak_ptrIT_EENS_9enable_ifIXsr14is_convertibleIPS6_PS2_EE5valueENS3_5__natEE4typeE
```

```
backtrace:
  native: pc 000000000031439c  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZNSt6__ndk110shared_ptrIN10libtorrent4upnpEEC2IS2_EERKNS_8weak_ptrIT_EENS_9enable_ifIXsr14is_convertibleIPS6_PS2_EE5valueENS3_5__natEE4typeE)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003104e8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
```
