### ISSUE TITLE
[crash] signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) dlfree - libcrypto.so/libssl.so related

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#166]
Introduced on May 29th 2017.

```
backtrace:
  native: pc 000000000001190c  /system/lib/libc.so (dlfree+1191)
  native: pc 000000000000ddab  /system/lib/libc.so (free+10)
  native: pc 0000000000083a33  /system/lib/libcrypto.so (CRYPTO_free+34)
  native: pc 000000000002f7c3  /system/lib/libssl.so (ssl_parse_serverhello_tlsext+738)
  native: pc 00000000000182d3  /system/lib/libssl.so (ssl3_get_server_hello+1018)
  native: pc 00000000000176c7  /system/lib/libssl.so (ssl3_connect+566)
  native: pc 000000000002806b  /system/lib/libssl.so (SSL_do_handshake+50)
  native: pc 000000000000c715  /system/lib/libjavacrypto.so
  native: pc 000000000002060c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
  native: pc 00000000000512ef  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
  native: pc 0000000000029aa0  /system/lib/libdvm.so
  native: pc 0000000000030f84  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
  native: pc 000000000002e61c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
  native: pc 0000000000063751  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
  native: pc 0000000000063775  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
  native: pc 0000000000058453  /system/lib/libdvm.so
  native: pc 000000000000d310  /system/lib/libc.so (__thread_entry+72)
  native: pc 000000000000d4a8  /system/lib/libc.so (pthread_create+240)
```
