### ISSUE TITLE
[Android] [1.2.0.8] [Crash]signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#167]
I am seeing a lot of these crashes in the app on playstore.

```
backtrace:
  native: pc 00000000003af528  /data/app/com.xyz.xyz-1/lib/arm/libjlibtorrent.so (_ZNK10libtorrent12piece_picker16has_piece_passedENS_3aux14strong_typedefIiNS1_15piece_index_tagEvEE+108)
```

**Comment by aldenml** [comment]
version?

**Comment by mianharisali** [comment]
12.0.8

**Comment by aldenml** [comment]
Ok, I'm in the process or releasing `1.2.0.9` and there are a lot of changes in `libtorrent`, I will notify you

**Comment by aldenml** [comment]
And...I just saw the version in the title :)

**Comment by aldenml** [comment]
@mianharisali `1.2.0.9` is out, give it a try and let us know

**Comment by mianharisali** [comment]
@aldenml still facing this issue.
here is the complete stack trace.





```
backtrace:
  native: pc 00000000003ed940  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so (_ZNK10libtorrent12piece_picker16has_piece_passedENS_3aux14strong_typedefIiNS1_15piece_index_tagEvEE+116)
  native: pc 000000000030bfec  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so (_ZN10libtorrent7torrent18set_piece_deadlineENS_3aux14strong_typedefIiNS1_15piece_index_tagEvEEii+88)
  native: pc 0000000000338d04  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so (_ZZNK10libtorrent14torrent_handle10async_callIMNS_7torrentEFvNS_3aux14strong_typedefIiNS3_15piece_index_tagEvEEiiEJRS6_RiSA_EEEvT_DpOT0_ENKUlvE_clEv+56)
  native: pc 0000000000338ed0  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so (_ZN5boost4asio6detail18completion_handlerIZNK10libtorrent14torrent_handle10async_callIMNS3_7torrentEFvNS3_3aux14strong_typedefIiNS7_15piece_index_tagEvEEiiEJRSA_RiSE_EEEvT_DpOT0_EUlvE_E11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationERKNS_6system10error_codeEm+88)
  native: pc 0000000000296814  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so (_ZN5boost4asio6detail15task_io_service10do_run_oneERNS1_11scoped_lockINS1_11posix_mutexEEERNS1_27task_io_service_thread_infoERKNS_6system10error_codeE+340)
  native: pc 0000000000296584  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so (_ZN5boost4asio6detail15task_io_service3runERNS_6system10error_codeE+152)
  native: pc 00000000002ba0ac  /data/app/com.xyz.xyz-1/lib/arm64/libjlibtorrent.so
  native: pc 0000000000065d64  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
  native: pc 000000000001ebc4  /system/lib64/libc.so (__start_thread+16)
```
