### ISSUE TITLE
OpenSSL 1.1.0f upgrade

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#176]
Not sure if it'll help with this common crash on Android (or if the crash is caused by bad use of OkHttpClient)

1.1.0f was made available in May 2017 according to the project, perhaps we have it already, couldn't find mention of it on FrostWire for android's changelog though.

```

backtrace:
  native: pc 00000000000118cc  /system/lib/libc.so (dlfree+1191)
  native: pc 000000000000dd4f  /system/lib/libc.so (free+10)
  native: pc 00000000000824a5  /system/lib/libcrypto.so (CRYPTO_free+24)
  native: pc 000000000002ac39  /system/lib/libssl.so (ssl_parse_serverhello_tlsext+244)
  native: pc 0000000000016c5d  /system/lib/libssl.so (ssl3_get_server_hello+924)
  native: pc 000000000001975f  /system/lib/libssl.so (ssl3_connect+642)
  native: pc 0000000000025109  /system/lib/libssl.so (SSL_do_handshake+72)
  native: pc 000000000000c6a9  /system/lib/libjavacrypto.so
  native: pc 0000000000020e8c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
  native: pc 0000000000051b2f  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
  native: pc 000000000002a320  /system/lib/libdvm.so
  native: pc 00000000000317d0  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
  native: pc 000000000002ee68  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
  native: pc 0000000000063f95  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
  native: pc 0000000000063fb9  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
  native: pc 0000000000058c8b  /system/lib/libdvm.so
  native: pc 000000000000d290  /system/lib/libc.so (__thread_entry+72)
  native: pc 000000000000d428  /system/lib/libc.so (pthread_create+240)
```
